-- Create the foods table
create table foods (
  id bigint generated by default as identity primary key,
  name text not null unique,
  calories int,
  protein float,
  carbs float,
  fat float
);

-- Enable Row Level Security (RLS)
alter table foods enable row level security;

-- Create a policy that allows anyone to read the foods table
create policy "Public foods are viewable by everyone"
  on foods for select
  using ( true );

-- Create a policy that allows authenticated users to insert (for seeding)
create policy "Authenticated users can insert foods"
  on foods for insert
  with check ( auth.role() = 'authenticated' or auth.role() = 'anon' ); -- allowing anon for easier seeding if needed, or restrict to service_role
